---

- name: Ensure directory /tmp/cci are exists
  file:
    path: /tmp/cci
    state: directory
    mode: 0755

- name: Install dependences
  yum:
    name: "{{ item }}"
    state: present #latest
  with_items:
      - glibc.i686
  when: ansible_os_family == 'RedHat'

- name: Copy install files
  copy:
    src: "{{ current_version }}/LINUX"
    dest: /tmp/cci

- name: Copy install files
  copy: 
    src: "{{ current_version }}/RMinstsh"
    dest: /tmp/cci
    mode: a+x

- shell: cpio -idmu < /tmp/cci/LINUX/RMHORC
  args:
    chdir: /

- name: Install CCI
  shell: ./horcminstall.sh
  args:
    chdir: /HORCM/    

- name: Delete /tmp/cci directory
  file:
   path: /tmp/cci
   state: absent

#- name: Copy horcm config files
#  copy: 
#    src: "{{ item }}"
#    dest: /etc/
#  with_items:
#    - horcm300.conf
#    - horcm301.conf
#    - horcm500.conf
#    - horcm501.conf

- name: Copy horcm config files
  template: 
    src: "{{ item }}"
    dest: /etc/
  with_items:
    - horcm1.conf
    - horcm2.conf

#- debug:
#    msg: "It's necessary modify S/N of VSP Gx00 on horcm.conf files"